version: '3.7'
services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack:0.12.8 # localstack/localstack:latest for PRO
    hostname: localstack
    network_mode: bridge
    ports:
      - "80:80"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
    environment:
      - SERVICES=lambda,dynamodb,s3,sqs,sns
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data  
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=true
      - LAMBDA_REMOVE_CONTAINERS=true
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./bin:/docker-entrypoint-initaws.d
  #  env_file: .env

  # container for lambda func to copy files in s3
  # s3-copy-lambda:
  #   image: s3-copy-lambda:latest
  #   build:
  #     context: ../lambdas/s3-copy-lambda
